// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBq8A1vCV02HE_yIcTDp4d6wtWhV1ivBVM',
    appId: '1:373353895913:web:f881a56b2ddf1617219d78',
    messagingSenderId: '373353895913',
    projectId: 'hershield-ef18c',
    authDomain: 'hershield-ef18c.firebaseapp.com',
    storageBucket: 'hershield-ef18c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfA6lTMNNUuj_vN3VpMNTTJuUKEPqvohg',
    appId: '1:373353895913:android:6a4eb74bd41f5142219d78',
    messagingSenderId: '373353895913',
    projectId: 'hershield-ef18c',
    storageBucket: 'hershield-ef18c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAx1GrCbk5GC6fKbc0sJfoMka8VPiWC1Xk',
    appId: '1:373353895913:ios:586882422be84d85219d78',
    messagingSenderId: '373353895913',
    projectId: 'hershield-ef18c',
    storageBucket: 'hershield-ef18c.appspot.com',
    iosBundleId: 'com.example.hershield',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAx1GrCbk5GC6fKbc0sJfoMka8VPiWC1Xk',
    appId: '1:373353895913:ios:586882422be84d85219d78',
    messagingSenderId: '373353895913',
    projectId: 'hershield-ef18c',
    storageBucket: 'hershield-ef18c.appspot.com',
    iosBundleId: 'com.example.hershield',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBq8A1vCV02HE_yIcTDp4d6wtWhV1ivBVM',
    appId: '1:373353895913:web:266a21a27cf7b099219d78',
    messagingSenderId: '373353895913',
    projectId: 'hershield-ef18c',
    authDomain: 'hershield-ef18c.firebaseapp.com',
    storageBucket: 'hershield-ef18c.appspot.com',
  );
}
